# 网站配置
title: Andy的GNSS工坊
description: 多年嵌入式实战经验，知识分享，拒绝重复造轮子！
baseurl: "/gnss-workshop.github.io" # 对于非username.github.io仓库，设置为/仓库名
url: "https://shenqislx.github.io" # 您的GitHub用户名.github.io

# theme: minima

# 插件
gems:
  - jekyll-feed

# 排除文件
exclude:
  - README.md
  - LICENSE
  - .vscode/

# Markdown处理
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  math_engine_opts: {}
  input: GFM
  parse_block_html: true

# 其他配置
collections:
  articles:
    output: true
    permalink: /articles/:name/