# 网站配置
title: Andy的GNSS工坊
description: 多年嵌入式实战经验，知识分享，拒绝重复造轮子！
baseurl: "" # 自定义域名根路径
url: "https://hqz.is-a.dev" # 站点公开访问地址

# theme: minima

# 插件
plugins:
  - jekyll-feed

feed:
  path: feed.xml
  collections:
    articles:
      path: /feed.xml

# 排除文件
exclude:
  - README.md
  - LICENSE
  - .vscode/

# Markdown处理
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  math_engine_opts: {}
  input: GFM
  parse_block_html: true

# 其他配置
collections:
  articles:
    output: true
    permalink: /articles/:name/
